name: flutter_mlkit_sandbox
description: "flutter mlkit sandbox"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  camera: ^0.11.0+2
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  google_mlkit_commons: ^0.9.0
  google_mlkit_face_detection: ^0.12.0
  google_mlkit_face_mesh_detection: ^0.3.0
  google_mlkit_selfie_segmentation: ^0.9.0
  image_picker: ^1.1.2
  path: ^1.9.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
